[package]
name = "confidential_payroll_management"
#name = "easy_private_voting_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.0", directory = "noir-projects/aztec-nr/aztec" }
#aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/aztec-nr/aztec" }
token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.0", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
#token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
