[package]
name = "confidential_payroll_management"
#name = "easy_private_voting_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.0", directory = "noir-projects/aztec-nr/aztec" }
#aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/aztec-nr/aztec" }

### The "Token Contract" from the Defi Wonderland Repository
token = { git = "https://github.com/defi-wonderland/aztec-standards", tag = "v1.2.1", directory = "src/token_contract" }

### The "Token Contract" from the Aztec Packages
#token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.0", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }
#token = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.3", directory = "noir-projects/noir-contracts/contracts/app/token_contract" }