"verification_key" = [
    "0x..........................",
    "0x.........................."
]

"proof"= [
    "0x..........................",
    "0x.........................."
]

"public_inputs"= [
    "0x.........................."
]

"key_hash"= "0x.........................."

"input_aggregation_object"= [
    "0x..........................",
    "0x.........................."
]
