[package]
name = "openbanking_escrow"
type = "contract"
authors = ["Mach 34"]

[dependencies]
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.2", directory="noir-projects/aztec-nr/authwit"}
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0-alpha-testnet.2", directory="noir-projects/aztec-nr/aztec" }
openbanking_verifier = { path = "../../lib" }
token = { git="https://github.com/nemi-fi/aztec-token", tag="main" }